export const actionTypes = <const>{
  PHONE_NUMBER_AUTHENTICATION_REQUEST: "PHONE_NUMBER_AUTHENTICATION_REQUEST",
  PHONE_NUMBER_AUTHENTICATION_SUCCESS: "PHONE_NUMBER_AUTHENTICATION_SUCCESS",
  PHONE_NUMBER_AUTHENTICATION_FAILURE: "PHONE_NUMBER_AUTHENTICATION_FAILURE",
  OTP_AUTHENTICATION_REQUEST: "OTP_AUTHENTICATION_REQUEST",
  OTP_AUTHENTICATION_SUCCESS: "OTP_AUTHENTICATION_SUCCESS",
  OTP_AUTHENTICATION_FAILURE: "OTP_AUTHENTICATION_FAILURE",
  SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
};
