export const actionTypes = <const>{
  PHONE_NUMBER_AUTHENTICATION_REQUEST: "PHONE_NUMBER_AUTHENTICATION_REQUEST",
  PHONE_NUMBER_AUTHENTICATION_SUCCESS: "PHONE_NUMBER_AUTHENTICATION_SUCCESS",
  PHONE_NUMBER_AUTHENTICATION_FAILURE: "PHONE_NUMBER_AUTHENTICATION_FAILURE",
  OTP_AUTHENTICATION_REQUEST: "OTP_AUTHENTICATION_REQUEST",
  OTP_AUTHENTICATION_SUCCESS: "OTP_AUTHENTICATION_SUCCESS",
  OTP_AUTHENTICATION_FAILURE: "OTP_AUTHENTICATION_FAILURE",
};
